name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Ajusta la ruta si el .csproj no está en raíz
      - name: Publish .NET Project
        run: dotnet publish ./Sudoku.Web.csproj -c Release -o release --nologo

      # Pone el base al nombre exacto del repo (respeta mayúsculas)
      - name: Set base href to repo name
        run: |
          REPO="${{ github.event.repository.name }}"
          sed -i "s|<base href=\"/\" />|<base href=\"/${REPO}/\" />|g" release/wwwroot/index.html

      - name: Copy 404.html for SPA refresh
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Disable Jekyll
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
