name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish .NET Project (Web)
        run: dotnet publish ./Sudoku.Web/Sudoku.Web.csproj -c Release -o release --nologo

      - name: Set base href to repo name (case-sensitive)
        run: |
          REPO="${{ github.event.repository.name }}"
          sed -i "s|<base href=\"/\" />|<base href=\"/${REPO}/\" />|g" release/wwwroot/index.html

      - name: SPA 404 + disable Jekyll
        run: |
          cp release/wwwroot/index.html release/wwwroot/404.html
          touch release/wwwroot/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
